version: '3.8'

services:
  start-page:
    container_name: start-page
    image: sunwavesun/start-page
    restart: unless-stopped
    ports:
      - 8080:3000
    volumes:
      - data:/app/data

volumes:
  data:
    name: start-page